version: '3.8'

services:
  db:
    image: "postgres:alpine"
    networks:
      - network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  rust:
    build: .
    networks:
      - network
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}
    command: ["/wait-for-it.sh", "${POSTGRES_DB}", "--", "/site"]

networks:
  network:
